export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const ORDER_BY_STOCK = 'ORDER_BY_STOCK';