export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const ORDER_BY_STOCK = 'ORDER_BY_STOCK';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const GET_DETAIL = 'GET_DETAIL';
export const DELETE_PRODUCT = 'DELETE PRODUCT';
export const PRODUCTS_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCTS_EDIT_FAILURE = 'PRODUCT_EDIT_FAILURE';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART';
export const SET_CART = 'SET_CART';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_TO_FAVORITES = 'REMOVE_TO_FAVORITES';
export const SET_FAVORITES = 'SET_FAVORITES';

export const ADD_ADMIN_USER_SUCCESS = 'ADD_ADMIN_USER_SUCCESS';
export const ADD_ADMIN_USER_FAILURE = 'ADD_ADMIN_USER_FAILURE';

export const GET_ADMIN_USERS_SUCCESS = 'GET_ADMIN_USERS_SUCCESS';
export const GET_ADMIN_USERS_FAILURE = 'GET_ADMIN_USERS_FAILURE';

export const GET_CLIENT_USERS_SUCCESS = 'GET_CLIENT_USERS_SUCCESS';
export const GET_CLIENT_USERS_FAILURE = 'GET_CLIENT_USERS_FAILURE';

export const SHOW_SUCCESS_ALERT = 'SHOW_SUCCESS_ALERT';
export const HIDE_SUCCESS_ALERT = 'HIDE_SUCCESS_ALERT';

export const SHOW_ERROR_ALERT = 'SHOW_SUCCESS_ALERT';
export const HIDE_ERROR_ALERT = 'SHOW_SUCCESS_ALERT';

export const INCREMENT_CART_COUNT = 'INCREMENT_CART_COUNT';
export const DECREMENT_CART_COUNT = 'DECREMENT_CART_COUNT';
export const DECREMENT_ALL = 'DECREMENT_ALL';

export const ADD_USER_DATA = 'ADD_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS';
export const GET_PRODUCT_REVIEWS_ERROR = 'GET_PRODUCT_REVIEWS_ERROR'

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';