export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const ORDER_BY_STOCK = 'ORDER_BY_STOCK';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const GET_DETAIL = 'GET_DETAIL';
export const DELETE_PRODUCT = 'DELETE PRODUCT';
export const PRODUCTS_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCTS_EDIT_FAILURE = 'PRODUCT_EDIT_FAILURE';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART';
export const SET_CART = 'SET_CART';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_TO_FAVORITES = 'REMOVE_TO_FAVORITES';
export const SET_FAVORITES = 'SET_FAVORITES';